### ISSUE TITLE
0xmons lore contest, 0.05 eth for top 3 best entries

### ISSUE THREAD

**Issue by sudo-owen** [0xmons/TODO#58]
1. pick a 0xmon you like
2. write something that expands upon the lore
3. OR
4. pick something mentioned in the lore
5. write more about it
6. 500-2000 words (soft limits)

**Comment by nerdRAGE-ETH** [comment]
Ok, I'll get this started: Fhuvlrgh 

Existing lore: A gigantic, elongated entity with one gigantic eye and two long, hairy tendrils. It is described as being constantly screaming, and haunting the dreams of all who see it.

Expanded lore:

Formed inside a black hole, Fhuvlrgh is not bound by the traditional laws of physics. It erupted forth from the event horizon, dissolving it’s host in a great flash of energy; a violent birth. Suddenly lacking the gravity to hold itself together, countless stars and civilizations were flung into the void of space as it’s host galaxy dissolved.

Fhuvlrgh roams the universe, looking only to feed. As Fhuvlrgh’s tentacles entangle its prey, time collapses, drawing out all usable energy for consumption. Nothing remains but inert dust; to an outside observer the process is instantaneous, but its victims perceive themselves forever frozen in time, aware but unable to move or act during their last terrified moment. 

The living embodiment of entropy, a loud static “screaming” is emitted as waste, along with heat, dust, and brilliant color. Legends say that the noise are the echoes of its past victims, frozen in perpetual agony. The reality is even more grim; Fhuvlrgh’s wails are background noise from the inevitable heat death of the universe.
