### ISSUE TITLE
Unable to see staked XMON or DOOM balance in Coinbase Wallet

### ISSUE THREAD

**Issue by matthewpavkov** [0xmons/TODO#70]
I staked XMON through the 0xmons website approximately 2 weeks ago. However, sometime after that, the 0xmons website stopped displaying my staked XMON and DOOM balance - it just shows zeros for everything, almost as if my wallet is not connected.

Notes:

- I'm using Coinbase Wallet (iOS, version 24.0.478)
- I've verified on Etherscan that my transactions all look fine
- I noted that my address appears in the `doomAmounts.json` file posted in Discord on 3/28/2021
- I've connected with another wallet address via Coinbase Wallet (in the in-app browser) and the website behaves as if I'm not connected to the network: I can't see staked ETH LP, I don't see the farming countdown, etc. Same situation with my wallet that has the staked XMON
- When I connect to the 0xmons website with MetaMask, the website acts normally (I see staked ETH LP, etc.)

There have been 3 recent Coinbase Wallet updates to the iOS app:

- version 23.8, ~3 weeks ago
- version 23.9, ~2 weeks ago
- version 24.0, ~1 week ago

I'm not sure exactly when I was no longer able to see my staked XMON in the Coinbase Wallet in-app browser, but it's likely it was about ~1 week ago, which nearly coincides with the iOS app update to 24.0.

I've attempted to connect my wallet to the 0xmons website from a desktop browser, however, there's no way to do it from what I've been able to find.

I'm happy to provide more information, help troubleshoot, etc. Just let me know how I can help.

Attached some screenshots.

![home](https://user-images.githubusercontent.com/2585198/112764948-cbcf4b00-8fd8-11eb-8641-28a1099f7fa6.jpg)
![staking-1](https://user-images.githubusercontent.com/2585198/112764949-cbcf4b00-8fd8-11eb-9313-7c9245c67368.jpg)
![staking-2](https://user-images.githubusercontent.com/2585198/112764950-cc67e180-8fd8-11eb-9456-b967fe073296.jpg)
![farming](https://user-images.githubusercontent.com/2585198/112764946-cbcf4b00-8fd8-11eb-9fbd-2f2e4c26e4a2.jpg)

**Comment by sudo-owen** [comment]
Hey Matthew! Thank you for the detailed info. 

Unfortunately, I don't know much about wallet integrations, so it will be a while before I can try to tackle this issue. I'll leave this issue as-is until then (won't close).

**Comment by matthewpavkov** [comment]
This issue should be closed as not reproducible. Somewhere along the way, this was fixed or otherwise addressed. I don't see any issues with Coinbase Wallet and interacting with the 0xmons.xyz website.
